#!/usr/bin/env python

import argparse

parser = argparse.ArgumentParser(description="Example conversation.")

# Add arguments
parser.add_argument("--name", "-n", type=str, default="example", help="Conversation name")
parser.add_argument("--enact", action="store_true", help="Do not log to MlflowSet this flag to enact the conversation history (meaning the the AI agents re-generate their parts).")

# Parse arguments
args = parser.parse_args()

from openai import OpenAI
import os
import yaml

from agent import TestAgent, HumanAgent
from conversation import InteractiveConversation

######### Boilerplate

api_url = os.environ.get("CHATUIT_BASE_URL", "http://127.0.0.1:1234/v1/")
api_key = os.environ.get("CHATUIT_API_KEY", "")

client = OpenAI(base_url=api_url,
                api_key=api_key,
                )

# models.yaml is generated by scripts/scan_models.py
with open("models.yaml", "r", encoding="utf-8") as f:
    models = yaml.safe_load(f)

# We pick the first one as an example
#model = models[5]
model = "gpt-4.1-mini"
print(model)

assert model in models

########

# We create 3 agents:
# - 1 human directing the conversation
# - 2 AI agents
h1 = HumanAgent("Albert")
a1 = TestAgent("A", client, model)
a2 = TestAgent("B", client, model)

# We create a conversation instance
conv = InteractiveConversation([a1, a2, h1], conversation_name=args.name)
# and we start it.
# If the conversation existed already in output/<name>.yaml, it is replayed.
# Otherwise, a new conversation is started
conv.start(enact=args.enact)
# The conversation is saved in output/<name>.yaml

